global using System.Reflection;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using FluentValidation;
global using Shared.Entities;
global using Shared.Data;
global using Shared.Repositories;
global using Shared.EntityConfigurations;
global using Shared.Helpers;
